pipeline:
  name: python-flask-docker-app
  identifier: pythonflaskdockerapp
  projectIdentifier: pythonflaskdockerapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        repoName: account.python-flask-docker-app
        build: <+input>
  stages:
    - stage:
        name: Build Test Push
        identifier: Build_Test_Push
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              connectorRef: docker-delegate
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to Docker Hub
                  identifier: Build_And_Push
                  spec:
                    connectorRef: dockerconnector
                    repo: <your-dockerhub-username>/python-flask-docker-app
                    tags:
                      - latest
              - step:
                  type: Semgrep
                  name: Run Semgrep Scan
                  identifier: Semgrep_Scan
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                    mode: orchestration
                    config: default
              - step:
                  type: Gitleaks
                  name: Run Gitleaks Scan
                  identifier: Gitleaks_Scan
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                    mode: orchestration
                    config: default
          sharedPaths: []
        when:
          pipelineStatus: Success
        delegateSelectors:
          - docker-delegate
